# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  bench:
    desc: run benchmark
    cmds:
      - go test -bench=. -benchmem -memprofile mem.prof -cpuprofile cpu.prof -run="^$" .
